services:
  web:
    # restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --chdir=/app/src --bind :8000 --workers 3 config.wsgi:application
    volumes:
      - .:/app
      - staticfiles:/app/src/static/
    expose:
      - 8000
    env_file:
      - ./env/.prod.env
  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/app/src/static/
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  staticfiles:
