FROM python:latest

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.prod.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.prod.txt


COPY ./entrypoint.prod.sh /app/entrypoint.prod.sh

COPY . /app/


ENTRYPOINT ["/app/entrypoint.prod.sh"]