# Generated by Django 4.0.4 on 2022-05-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='dashboard.document'),
        ),
    ]
