# Generated by Django 4.0.4 on 2022-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_document_executiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='security_manual',
            field=models.BooleanField(default=False),
        ),
    ]
